/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulb.lisa.fhir.client;

import java.util.ArrayList;
import org.hl7.fhir.dstu3.model.Patient;

/**
 *
 * @author Adrien Foucart
 */
public class MainWindow extends javax.swing.JFrame {
    
    private final FHIRClient fhirClient;
    private ArrayList<Patient> patients = new ArrayList();
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        fhirClient = new FHIRClient();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameSearch = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        IDSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientInfoPanel = new javax.swing.JTextArea();
        searchIDButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchResultList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                searchResultListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(searchResultList);

        jLabel2.setText("ID:");

        patientInfoPanel.setColumns(20);
        patientInfoPanel.setRows(5);
        jScrollPane2.setViewportView(patientInfoPanel);

        searchIDButton.setText("Search");
        searchIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)
                        .addGap(263, 263, 263)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchIDButton)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel2)
                    .addComponent(IDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchIDButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        patients = fhirClient.searchPatientsByName(nameSearch.getText());
        
        PatientListModel plm = new PatientListModel(patients);
        searchResultList.setModel(plm);
        searchResultList.repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchResultListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_searchResultListValueChanged
        if( evt.getValueIsAdjusting() ) return;
        int idx = searchResultList.getSelectedIndex();
        
        Patient p = patients.get(idx);
        
        IDSearch.setText(p.getIdElement().getIdPart());
    }//GEN-LAST:event_searchResultListValueChanged

    private void searchIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIDButtonActionPerformed
        Patient p = fhirClient.getPatientById(IDSearch.getText());
        
        if( p == null ){
            patientInfoPanel.setText("No patient found with this id.");
            return;
        }
        
        String patientInfo = "Name: " + p.getNameFirstRep().getFamily() + " " + p.getNameFirstRep().getGivenAsSingleString() + "\n";
        if( p.getAddressFirstRep() != null ){
            patientInfo += "Address: \n";
            patientInfo += p.getAddressFirstRep().getPostalCode() + " " + p.getAddressFirstRep().getCity() + "\n";
        }
        if( p.getGender() != null ){
            patientInfo += "Gender: " + p.getGender().getDisplay() + "\n";
        }
        
        patientInfoPanel.setText(patientInfo);
    }//GEN-LAST:event_searchIDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameSearch;
    private javax.swing.JTextArea patientInfoPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchIDButton;
    private javax.swing.JList<String> searchResultList;
    // End of variables declaration//GEN-END:variables
}
